//vehbuy
#define vehbuytext1 "Вы в долгах, и еще не можете приобрести никакой грузовик."
#define vehbuytext2 "Магазин открывается после 50 очков доставки."
#define vehbuytext3 "Нельзя купить новый грузовик во время доставки."
#define vehbuytext4 "{FFFFFF}Посредством кнопок {FFFF00}[NUM 4] {FFFFFF}и{FFFF00}[NUM 6]{FFFFFF} выберите грузовик\n\
					Закрепите результат с помощью кнопки {FFFF00}[Y]\n\
					{FFFFFF}Что бы выйти используйте кнопку {FFFF00}[N]\n\
					{FFFFFF}За ваш старый грузовик после покупки нового вы получили компинсацию(относительно его износа) - $"
#define vehbuytext5 "Покупка нового грузовика"
#define vehbuytext6 "Вы слишком далеко от ближайшего магазина грузовиков."
#define vehbuytext7 "Выбор грузовика"
#define vehbuytext8 "У вас недостаточно очков, что бы преобрести данный грузовик"
#define vehbuytext9 "У вас недостаточно денег, что бы купить данный грузовик"
#define vehbuytext10 "Вы купили грузовик %s\nЦена %d $\nЗа ваш старый грузовик вы выручили %d $"
#define vehbuytext11 "Покупка грузовика"
#define vehbuytext12 "~b~trucker.valakas.ru ~r~/help"
#define vehbuytext13 "~b~trucker.valakas.ru ~r~/help             ~y~Mashina:~w~%s ~r~Budet dostupna posle %d ochkov dostavki"
#define vehbuytext14 "~b~trucker.valakas.ru ~r~/help             ~y~Mashina:~w~%s ~y~Cena:~w~%d$ ~y~Vmestimost'(kg):~w~%d"
